kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: osiris
spec:
  clusterIP: None
  ports:
  - port: 27017
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mongodb
  namespace: osiris
subsets:
  - addresses:
        - ip: 192.168.0.22
    ports:
      - port: 27017
        name: mongodb