apiVersion: apps/v1
kind: Deployment
metadata:
  name: publications-service
  namespace: osiris
spec:
  replicas: 1
  selector:
    matchLabels:
     pod-name: publications-service
  template:
    metadata:
      labels:
        pod-name: publications-service
    spec:
      containers:
      - name: publications-service
        image: "docker.io/mightyfoxx/publications-service:v1.01"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          protocol: TCP
          containerPort: 8000
        env:
          - name: DATABASE_URL
            value: mongodb://ren:Lollipop17@mongodb:27017/
          - name: COLLECTION_NAME
            value: publications
          - name: DB_NAME
            value: publication-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"