apiVersion: v1
kind: Service
metadata:
  name: publications-service
  namespace: osiris
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    pod-name: publications-service
  type: NodePort