name: Docker Image Build & Push

on:
  push:
    paths:
    - src/**
    - Dockerfile

#env:
#  TAG: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Dynamically set MY_DATE environment variable
    #  run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mightyfoxx/osiris_publications-management:latest
   
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push mightyfoxx/osiris_publications-management:latest
    
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: Yoann-Renard/Osiris-NFT_Publications-Management
        event-type: trigger-deployment
